---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/ephemeralcontainers
  - pods/log
  - services
  verbs:
  - '*'
- apiGroups:
  - dm.cr.kanister.io
  resources:
  - datamoversessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dm.cr.kanister.io
  resources:
  - datamoversessions/finalizers
  verbs:
  - update
- apiGroups:
  - dm.cr.kanister.io
  resources:
  - datamoversessions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - '*'
